Fix PZ wrapper active agents calculation
oxwhirl/smac pull request #81
Opened 2021-08-30 17:02 UTC by KaleabTessera

PettingZoo uses `self.agents` to keep track of the active agents in the environment. In the Smac wrapper, `self.agents` is updated before `self.env.step`, meaning that `self.agents` is always a step behind. This results in  `all_observes` including information from dead agents and it makes it difficult/impossible to know when the env is done when using the PZ wrapper (the usual env_done check is seeing if `self.agents` is empty). 

Full discussion - https://github.com/instadeepai/Mava/issues/297. @rodrigodelazcano @benblack769

2021-09-06 23:17 UTC, benblack769 commented
Thanks for doing this. Once the PZ tests are updated to check that this correctly implements the PZ API ([in progress here](https://github.com/PettingZoo-Team/PettingZoo/pull/458), this will be a change I would support merging.

2021-09-07 09:46 UTC, samvelyan commented
Thanks @KaleabTessera for your contribution. @rodrigodelazcano could you please review this?

2021-09-11 20:51 UTC, rodrigodelazcano requested changes
with these changes, the iteration through self.possible_agents can now be done only through self.agents and reduce computation time.

2021-09-11 20:51 UTC, rodrigodelazcano commented on smac/env/pettingzoo/StarCraft2PZEnv.py
>          for agent in self.possible_agents:
with these changes, the iteration through `self.possible_agents` can now be done only through `self.agents` and reduce computation time.

2021-09-15 10:21 UTC, KaleabTessera commented on smac/env/pettingzoo/StarCraft2PZEnv.py
>          for agent in self.possible_agents:
I updated this. @rodrigodelazcano

2021-09-15 10:26 UTC, KaleabTessera commented
> Thanks @KaleabTessera for making the PR. However, I would prefer to wait until this issue [PettingZoo-Team/PettingZoo#464](https://github.com/PettingZoo-Team/PettingZoo/issues/464) is resolved and @benblack769 approves as well.

Okay, just let me know if you want me to change anything @rodrigodelazcano @benblack769 :+1:

2021-09-16 03:36 UTC, rodrigodelazcano commented
Sure thing! Thank you for your interest @KaleabTessera

2021-09-28 06:51 UTC, KaleabTessera commented
@rodrigodelazcano This issue https://github.com/PettingZoo-Team/PettingZoo/issues/464 seems to be closed. Can you review this PR now?

2021-10-13 06:43 UTC, KaleabTessera commented
@benblack769 Just a friendly ping on this. :+1:

2021-10-13 07:10 UTC, benblack769 commented
Ah, yes, thanks for the ping, I lost track of this. The intended change was made and released in pettingzoo 1.12.0

The agents list should now represent the agents that should take the next step in the environment. 

I think the next step is to check that the [API test for the SMAC pettingzoo wrapper](https://github.com/oxwhirl/smac/blob/master/smac/env/pettingzoo/test/all_test.py) passes, and if so, then this PR should be good.

2021-11-05 20:53 UTC, benblack769 commented
@KaleabTessera I went ahead and made the wrapper comply with the pettingzoo API tests here: #84 

Thanks for your work on this, your insights here really pushed a full API change to the whole pettingzoo ecosystem.

2021-11-12 11:29 UTC, closed without merging